services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: restoran_app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=restoran
      - REDIS_HOST=redis
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
    networks:
      - restoran
    depends_on:
      - mysql
      - redis

  queue:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: restoran_queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=restoran
      - REDIS_HOST=redis
    networks:
      - restoran
    depends_on:
      - mysql
      - redis
