name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/laravel-base.yml
    with:
      db-database: restoran_test
    secrets: inherit
