name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/laravel-base.yml
    with:
      db-database: restoran_test
    secrets:
      vps-host: ${{ secrets.VPS_HOST }}
      vps-user: ${{ secrets.VPS_USER }}
      vps-port: ${{ secrets.VPS_PORT }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
